<?php
return array(
    "database"=>array(
        "host"=>"localhost",
        "username"=>"root",
        "password"=>123456,
        "dbname"=>"wui2006",
        "port"=>3306
    ),
    "smarty"=>array(
        "templatedir"=>TPL_PATH,
        "compiledir"=>COMP_PATH,
        "cachedir"=>CACHE_PATH,

    ),
    "code"=>array(
        "type"=>"png",
   "width"=>160,
    "height"=>50,
    "codelen"=>4,
   "seed"=>"abcdefhkmnoprstuvwxyzABCDEFGHKLMNOPRSTUVWXYZ345678",
   "fontsize"=>array("min"=>20,"max"=>35),
    "fontangle"=>array("min"=>-15,"max"=>15),
    "linenum"=>array("min"=>1,"max"=>5),
    "linewidth"=>array("min"=>1,"max"=>3),
   "pixnum"=>array("min"=>80,"max"=>150),
    "fontfile"=>"E:\wamp64\www\php\mvc\application\static/font/demo.TTF",
        "ischeck"=>false,
),
);
